p = input("enter the principle amount")
p = int(p)
r = input("enter the rate of interest")
r = float(r)
t = input("enter the time period")
t = int(t)
ci = p*pow((1 + (r/100)),t)
ci = float(ci)
print("the compound interest is",ci)
